/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicprojectsprototype.presentation.admin;

import co.edu.unicauca.academicprojectsprototype.domain.entities.Coordinator;
import co.edu.unicauca.academicprojectsprototype.domain.services.AdminService;
import co.edu.unicauca.academicprojectsprototype.domain.services.CompanyService;
import co.edu.unicauca.academicprojectsprototype.domain.services.CoordinatorService;
import co.edu.unicauca.academicprojectsprototype.domain.services.StudentService;
import co.edu.unicauca.academicprojectsprototype.infra.Messages;
import co.edu.unicauca.academicprojectsprototype.presentation.GUIHomeWithoutLog;
import javax.swing.table.DefaultTableModel;
import observer.IObserver;

/**
 *
 * @author lopez
 */
public class RequestCoordinators extends javax.swing.JFrame implements IObserver{

    private CompanyService companyService;
    private StudentService studentService;
    private CoordinatorService coordiService;
    private Coordinator coordinadorSeleccionado;
    AdminService adminService;

    /**
     * Creates new form RequestCoordinators
     */
    public RequestCoordinators() {
        this.companyService = CompanyService.getInstance(null);
        this.studentService = StudentService.getInstance(null);
        this.coordiService = CoordinatorService.getInstance(null);
        this.adminService = AdminService.getInstance();
        coordiService.addObserver(this);
        initComponents();
        fillHistoryCoordinators();
        fillRequestCoordinators();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupValidarCoordi = new javax.swing.ButtonGroup();
        jPContent = new javax.swing.JPanel();
        jPCoordi = new javax.swing.JPanel();
        jLCoordinator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistoryCoordi = new javax.swing.JTable();
        jPCoordiSinEstado = new javax.swing.JPanel();
        jLSolisSinAtender = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSoliCoordi = new javax.swing.JTable();
        jLNombreCoordi = new javax.swing.JLabel();
        jPValidarCoordi = new javax.swing.JPanel();
        jRBtnAceptar = new javax.swing.JRadioButton();
        jRBtnRechazar = new javax.swing.JRadioButton();
        jBtnProcesarSoli = new javax.swing.JButton();
        jPButtom = new javax.swing.JPanel();
        jBtnBackHomeWithLogin = new javax.swing.JButton();
        jPHead = new javax.swing.JPanel();
        iconLoginUser = new javax.swing.JLabel();
        jLTitittleLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPCoordi.setBackground(new java.awt.Color(255, 255, 255));

        jLCoordinator.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCoordinator.setForeground(new java.awt.Color(0, 0, 0));
        jLCoordinator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCoordinator.setText("Historial de solicitudes de coordinarores:");

        jTableHistoryCoordi.setBackground(new java.awt.Color(255, 255, 255));
        jTableHistoryCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableHistoryCoordi.setForeground(new java.awt.Color(0, 0, 0));
        jTableHistoryCoordi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableHistoryCoordi);

        javax.swing.GroupLayout jPCoordiLayout = new javax.swing.GroupLayout(jPCoordi);
        jPCoordi.setLayout(jPCoordiLayout);
        jPCoordiLayout.setHorizontalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPCoordiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCoordinator, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCoordiLayout.setVerticalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCoordinator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPContent.add(jPCoordi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 450));

        jPCoordiSinEstado.setBackground(new java.awt.Color(255, 255, 255));

        jLSolisSinAtender.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLSolisSinAtender.setForeground(new java.awt.Color(0, 0, 0));
        jLSolisSinAtender.setText("Solicitudes ");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTableSoliCoordi.setBackground(new java.awt.Color(255, 255, 255));
        jTableSoliCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableSoliCoordi.setForeground(new java.awt.Color(0, 0, 0));
        jTableSoliCoordi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSoliCoordi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSoliCoordiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSoliCoordi);

        javax.swing.GroupLayout jPCoordiSinEstadoLayout = new javax.swing.GroupLayout(jPCoordiSinEstado);
        jPCoordiSinEstado.setLayout(jPCoordiSinEstadoLayout);
        jPCoordiSinEstadoLayout.setHorizontalGroup(
            jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiSinEstadoLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLSolisSinAtender)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCoordiSinEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPCoordiSinEstadoLayout.setVerticalGroup(
            jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiSinEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSolisSinAtender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        jPContent.add(jPCoordiSinEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 520, 260));

        jLNombreCoordi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLNombreCoordi.setForeground(new java.awt.Color(0, 0, 0));
        jLNombreCoordi.setText("NOMBRE COORDI");
        jPContent.add(jLNombreCoordi, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        jPValidarCoordi.setBackground(new java.awt.Color(255, 255, 255));

        jRBtnAceptar.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroupValidarCoordi.add(jRBtnAceptar);
        jRBtnAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jRBtnAceptar.setText("Aceptar solicitud");

        jRBtnRechazar.setBackground(new java.awt.Color(255, 153, 153));
        buttonGroupValidarCoordi.add(jRBtnRechazar);
        jRBtnRechazar.setForeground(new java.awt.Color(0, 0, 0));
        jRBtnRechazar.setText("Rechazar Solicitud");

        jBtnProcesarSoli.setText("ACEPTAR");
        jBtnProcesarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcesarSoliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPValidarCoordiLayout = new javax.swing.GroupLayout(jPValidarCoordi);
        jPValidarCoordi.setLayout(jPValidarCoordiLayout);
        jPValidarCoordiLayout.setHorizontalGroup(
            jPValidarCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValidarCoordiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jRBtnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jRBtnRechazar)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPValidarCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnProcesarSoli)
                .addGap(130, 130, 130))
        );
        jPValidarCoordiLayout.setVerticalGroup(
            jPValidarCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValidarCoordiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPValidarCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnAceptar)
                    .addComponent(jRBtnRechazar))
                .addGap(18, 18, 18)
                .addComponent(jBtnProcesarSoli)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPContent.add(jPValidarCoordi, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 340, 110));

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackHomeWithLogin.setBackground(new java.awt.Color(236, 230, 240));
        jBtnBackHomeWithLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jBtnBackHomeWithLogin.setBorderPainted(false);
        jBtnBackHomeWithLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackHomeWithLoginActionPerformed(evt);
            }
        });
        jPButtom.add(jBtnBackHomeWithLogin);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new java.awt.GridBagLayout());

        iconLoginUser.setBackground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setForeground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginUser3.png"))); // NOI18N
        iconLoginUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPHead.add(iconLoginUser, gridBagConstraints);

        jLTitittleLogin.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLTitittleLogin.setForeground(new java.awt.Color(0, 0, 0));
        jLTitittleLogin.setText("Solicitudes de coordinadores - Sistema proyectos");
        jLTitittleLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitittleLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPHead.add(jLTitittleLogin, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackHomeWithLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackHomeWithLoginActionPerformed
        GUIHomeWithoutLog HomeSinLogin = new GUIHomeWithoutLog();
        HomeSinLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBackHomeWithLoginActionPerformed

    private void jTableSoliCoordiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSoliCoordiMouseClicked
        int selectedRow = jTableSoliCoordi.getSelectedRow();
        if (selectedRow != -1) {
            String codigo = jTableSoliCoordi.getValueAt(selectedRow, 0).toString(); // Suponiendo que la primera columna es el código
            coordinadorSeleccionado = coordiService.Search(codigo);

            if (coordinadorSeleccionado != null) {
                jLNombreCoordi.setText(coordinadorSeleccionado.getName());
            }
        }

    }//GEN-LAST:event_jTableSoliCoordiMouseClicked

    private void jBtnProcesarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcesarSoliActionPerformed
        if (jRBtnAceptar.isSelected()) {
            adminService.aceptarCoordinador(coordinadorSeleccionado);
            coordiService.actualizarEstadoCoordinador(coordinadorSeleccionado.getCode(), coordinadorSeleccionado.getEstado());
        }
        if (jRBtnRechazar.isSelected()) {
            adminService.rechazarCoodinador(coordinadorSeleccionado);
            coordiService.actualizarEstadoCoordinador(coordinadorSeleccionado.getCode(), coordinadorSeleccionado.getEstado());
        }

        if (!(jRBtnAceptar.isSelected() || jRBtnRechazar.isSelected())) {
            Messages.showMessageDialog("Seleccione una opcion por favor", "Sin opcion");
        }
    }//GEN-LAST:event_jBtnProcesarSoliActionPerformed

    private void fillHistoryCoordinators() {
        DefaultTableModel modeloCoordi = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Telefono", "Email", "Programa Acacemico", "Estado"}, 0);
        modeloCoordi.setRowCount(0);

        if (coordiService.listAll() != null) {
            for (Coordinator coordi : coordiService.listAll()) {

                if (coordi.getName() != null && coordi.getCode() != null) {
                    modeloCoordi.addRow(new Object[]{coordi.getCode(), coordi.getName(), coordi.getPhone(), coordi.getEmail(), coordi.getProgramaAcademico(), coordi.getEstado()});
                }
                jTableHistoryCoordi.setModel(modeloCoordi);
            }
        }
    }

    private void fillRequestCoordinators() {
        DefaultTableModel modeloCoordi = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Email", "Programa Acacemico", "Estado"}, 0);
        modeloCoordi.setRowCount(0);

        if (coordiService.listAll() != null) {
            for (Coordinator coordi : coordiService.listAll()) {

                if (coordi.getName() != null && coordi.getCode() != null && coordi.getEstado().toString().equals("PENDIENTE")) {
                    modeloCoordi.addRow(new Object[]{coordi.getCode(), coordi.getName(), coordi.getEmail(), coordi.getProgramaAcademico(), coordi.getEstado()});
                }
                jTableSoliCoordi.setModel(modeloCoordi);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupValidarCoordi;
    private javax.swing.JLabel iconLoginUser;
    private javax.swing.JButton jBtnBackHomeWithLogin;
    private javax.swing.JButton jBtnProcesarSoli;
    private javax.swing.JLabel jLCoordinator;
    private javax.swing.JLabel jLNombreCoordi;
    private javax.swing.JLabel jLSolisSinAtender;
    private javax.swing.JLabel jLTitittleLogin;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPCoordi;
    private javax.swing.JPanel jPCoordiSinEstado;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPValidarCoordi;
    private javax.swing.JRadioButton jRBtnAceptar;
    private javax.swing.JRadioButton jRBtnRechazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHistoryCoordi;
    private javax.swing.JTable jTableSoliCoordi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        fillHistoryCoordinators();
        fillRequestCoordinators();
    }
}
