/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicprojectsprototype.presentation.admin;

import co.edu.unicauca.academicprojectsprototype.domain.entities.Company;
import co.edu.unicauca.academicprojectsprototype.domain.entities.Coordinator;
import co.edu.unicauca.academicprojectsprototype.domain.entities.Project;
import co.edu.unicauca.academicprojectsprototype.domain.entities.Student;
import co.edu.unicauca.academicprojectsprototype.domain.services.CompanyService;
import co.edu.unicauca.academicprojectsprototype.domain.services.CoordinatorService;
import co.edu.unicauca.academicprojectsprototype.domain.services.ICompanyService;
import co.edu.unicauca.academicprojectsprototype.domain.services.ICoordinatorService;
import co.edu.unicauca.academicprojectsprototype.domain.services.IStudentService;
import co.edu.unicauca.academicprojectsprototype.domain.services.StudentService;
import co.edu.unicauca.academicprojectsprototype.presentation.GUIHomeWithoutLog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lopez
 */
public class Users extends javax.swing.JFrame {

    private ICompanyService companyService;
    private IStudentService studentService;
    private ICoordinatorService coordiService;

    /**
     * Creates new form Users
     */
    public Users(ICompanyService serviceCompany, IStudentService serviceStudent, ICoordinatorService serviceCoordi) {
        this.companyService = CompanyService.getInstance(null);
        this.studentService = StudentService.getInstance(null);
        this.coordiService = CoordinatorService.getInstance(null);
        initComponents();
        fillCompanies();
        fillCoordinators();
        fillStudents();
    }

    public void fillStudents() {
        DefaultTableModel modeloStudent = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Telefono", "Email"}, 0);
        modeloStudent.setRowCount(0);

        for (Student student : studentService.listAll()) {

            if (student.getName() != null && student.getCode() != null) {
                modeloStudent.addRow(new Object[]{student.getCode(), student.getName(), student.getPhone(), student.getEmail()});
            }
            jTableStudent.setModel(modeloStudent);
        }
    }

    public void fillCompanies() {
        DefaultTableModel modeloCompani = new DefaultTableModel(new String[]{"NIT", "Nombre", "Telefono", "Page Web", "Sector", "Email"}, 0);
        modeloCompani.setRowCount(0);

        for (Company company : companyService.getAllCompanies()) {

            if (company.getName() != null && company.getNit() != null) {
                modeloCompani.addRow(new Object[]{company.getNit(), company.getName(), company.getPhone(), company.getPageWeb(), company.getSector(), company.getEmail()});

            }
            jTableCompany.setModel(modeloCompani);
        }
    }

    public void fillCoordinators() {
        DefaultTableModel modeloCoordi = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Telefono", "Email","Programa Acacemico","Estado"}, 0);
        modeloCoordi.setRowCount(0);

        for (Coordinator coordi : coordiService.listAll()) {

            if (coordi.getName() != null && coordi.getCode() != null) {
                modeloCoordi.addRow(new Object[]{coordi.getCode(), coordi.getName(), coordi.getPhone(), coordi.getEmail(),coordi.getProgramaAcademico(),coordi.getEstado()});
            }
            jTableCoordinator.setModel(modeloCoordi);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPContent = new javax.swing.JPanel();
        jPStudent = new javax.swing.JPanel();
        jLCoordinator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCoordinator = new javax.swing.JTable();
        jPCompany = new javax.swing.JPanel();
        jLStudent1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jPStudent1 = new javax.swing.JPanel();
        jLCompany1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCompany = new javax.swing.JTable();
        jPButtom = new javax.swing.JPanel();
        jBtnBackHomeWithLogin = new javax.swing.JButton();
        jPHead = new javax.swing.JPanel();
        iconLoginUser = new javax.swing.JLabel();
        jLTitittleLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPStudent.setBackground(new java.awt.Color(255, 255, 255));

        jLCoordinator.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCoordinator.setForeground(new java.awt.Color(0, 0, 0));
        jLCoordinator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCoordinator.setText("Coordinadores");

        jTableCoordinator.setBackground(new java.awt.Color(255, 255, 255));
        jTableCoordinator.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableCoordinator.setForeground(new java.awt.Color(0, 0, 0));
        jTableCoordinator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCoordinator);

        javax.swing.GroupLayout jPStudentLayout = new javax.swing.GroupLayout(jPStudent);
        jPStudent.setLayout(jPStudentLayout);
        jPStudentLayout.setHorizontalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLCoordinator, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jPStudentLayout.setVerticalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLCoordinator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPContent.add(jPStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 320, 450));

        jPCompany.setBackground(new java.awt.Color(255, 255, 255));

        jLStudent1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLStudent1.setForeground(new java.awt.Color(0, 0, 0));
        jLStudent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLStudent1.setText("Estudiantes");

        jTableStudent.setBackground(new java.awt.Color(255, 255, 255));
        jTableStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableStudent.setForeground(new java.awt.Color(0, 0, 0));
        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStudent);

        javax.swing.GroupLayout jPCompanyLayout = new javax.swing.GroupLayout(jPCompany);
        jPCompany.setLayout(jPCompanyLayout);
        jPCompanyLayout.setHorizontalGroup(
            jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCompanyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jPCompanyLayout.setVerticalGroup(
            jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCompanyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLStudent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPContent.add(jPCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 450));

        jPStudent1.setBackground(new java.awt.Color(255, 255, 255));

        jLCompany1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCompany1.setForeground(new java.awt.Color(0, 0, 0));
        jLCompany1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCompany1.setText("Empresas");

        jTableCompany.setBackground(new java.awt.Color(255, 255, 255));
        jTableCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableCompany.setForeground(new java.awt.Color(0, 0, 0));
        jTableCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCompany);

        javax.swing.GroupLayout jPStudent1Layout = new javax.swing.GroupLayout(jPStudent1);
        jPStudent1.setLayout(jPStudent1Layout);
        jPStudent1Layout.setHorizontalGroup(
            jPStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStudent1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLCompany1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jPStudent1Layout.setVerticalGroup(
            jPStudent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudent1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLCompany1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPContent.add(jPStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 320, 450));

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackHomeWithLogin.setBackground(new java.awt.Color(236, 230, 240));
        jBtnBackHomeWithLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jBtnBackHomeWithLogin.setBorderPainted(false);
        jBtnBackHomeWithLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackHomeWithLoginActionPerformed(evt);
            }
        });
        jPButtom.add(jBtnBackHomeWithLogin);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new java.awt.GridBagLayout());

        iconLoginUser.setBackground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setForeground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginUser3.png"))); // NOI18N
        iconLoginUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPHead.add(iconLoginUser, gridBagConstraints);

        jLTitittleLogin.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLTitittleLogin.setForeground(new java.awt.Color(0, 0, 0));
        jLTitittleLogin.setText("Listado usuarios - Sistema proyectos");
        jLTitittleLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitittleLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPHead.add(jLTitittleLogin, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackHomeWithLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackHomeWithLoginActionPerformed
        GUIHomeWithoutLog HomeSinLogin = new GUIHomeWithoutLog();
        HomeSinLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBackHomeWithLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLoginUser;
    private javax.swing.JButton jBtnBackHomeWithLogin;
    private javax.swing.JLabel jLCompany1;
    private javax.swing.JLabel jLCoordinator;
    private javax.swing.JLabel jLStudent1;
    private javax.swing.JLabel jLTitittleLogin;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPCompany;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPStudent;
    private javax.swing.JPanel jPStudent1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCompany;
    private javax.swing.JTable jTableCoordinator;
    private javax.swing.JTable jTableStudent;
    // End of variables declaration//GEN-END:variables
}
