/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicprojectsprototype.presentation;

import co.edu.unicauca.academicprojectsprototype.domain.entities.Project;
import co.edu.unicauca.academicprojectsprototype.domain.entities.Student;
import co.edu.unicauca.academicprojectsprototype.domain.services.ProjectService;
import co.edu.unicauca.academicprojectsprototype.domain.services.StudentService;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import observer.IObserver;

/**
 *
 * @author Sandino
 */
public class GUIAssignment extends javax.swing.JFrame implements IObserver{

    private StudentService studentService;
    private ProjectService projectService;
    private Student EstudianteSeleccionado;
    private Project ProjectoSeleccionado;

    public GUIAssignment() {
        initComponents();
        this.studentService = StudentService.getInstance(null);
        this.projectService = ProjectService.getInstance(null);
        this.projectService.addObserver(this);
        fillStudents();
        fillTableProject();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadiobuttonGroupSelecRol = new javax.swing.ButtonGroup();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPButtom = new javax.swing.JPanel();
        jBtnBackSelectUser = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPStudent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPProjects = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBtnSaveProject = new javax.swing.JButton();
        jLabelNameProject = new javax.swing.JLabel();
        jLStudent = new javax.swing.JLabel();
        jPTittleNewUser = new javax.swing.JPanel();
        jLTittleNewUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setForeground(new java.awt.Color(0, 0, 0));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setAlignment(java.awt.Label.CENTER);
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackSelectUser.setBackground(new java.awt.Color(236, 230, 240));
        jBtnBackSelectUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jBtnBackSelectUser.setBorderPainted(false);
        jBtnBackSelectUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackSelectUserActionPerformed(evt);
            }
        });
        jPButtom.add(jBtnBackSelectUser);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setForeground(new java.awt.Color(0, 0, 0));

        jPStudent.setBackground(new java.awt.Color(204, 204, 255));

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStudentMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableStudent);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione un estudiante");

        javax.swing.GroupLayout jPStudentLayout = new javax.swing.GroupLayout(jPStudent);
        jPStudent.setLayout(jPStudentLayout);
        jPStudentLayout.setHorizontalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPStudentLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPStudentLayout.setVerticalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStudentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPProjects.setBackground(new java.awt.Color(204, 204, 255));

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProjects);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seleccione un proyecto");

        javax.swing.GroupLayout jPProjectsLayout = new javax.swing.GroupLayout(jPProjects);
        jPProjects.setLayout(jPProjectsLayout);
        jPProjectsLayout.setHorizontalGroup(
            jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProjectsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPProjectsLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPProjectsLayout.setVerticalGroup(
            jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProjectsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBtnSaveProject.setBackground(new java.awt.Color(0, 0, 0));
        jBtnSaveProject.setFont(new java.awt.Font("Sans Serif Collection", 1, 24)); // NOI18N
        jBtnSaveProject.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveProject.setText("ASIGNAR");
        jBtnSaveProject.setToolTipText("");
        jBtnSaveProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveProjectActionPerformed(evt);
            }
        });

        jLabelNameProject.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelNameProject.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNameProject.setText("PROYECTO SELECCIONADO");

        jLStudent.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLStudent.setForeground(new java.awt.Color(0, 0, 0));
        jLStudent.setText("ESTUDIANTE SELECCIONADO");

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(417, 417, 417)
                .addComponent(jBtnSaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jLabelNameProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLStudent)
                .addGap(187, 187, 187))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPProjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameProject)
                    .addComponent(jLStudent))
                .addGap(48, 48, 48)
                .addComponent(jBtnSaveProject)
                .addGap(28, 28, 28))
        );

        jPTittleNewUser.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleNewUser.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewUser.setForeground(new java.awt.Color(0, 0, 0));
        jLTittleNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NewUser.png"))); // NOI18N
        jLTittleNewUser.setText("Nueva asignación");
        jLTittleNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPTittleNewUserLayout = new javax.swing.GroupLayout(jPTittleNewUser);
        jPTittleNewUser.setLayout(jPTittleNewUserLayout);
        jPTittleNewUserLayout.setHorizontalGroup(
            jPTittleNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTittleNewUserLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLTittleNewUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPTittleNewUserLayout.setVerticalGroup(
            jPTittleNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTittleNewUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTittleNewUser)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTittleNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTittleNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBackSelectUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackSelectUserActionPerformed
        GUIHomeWithoutLog homeWithOutLog = new GUIHomeWithoutLog();
        homeWithOutLog.setExtendedState(JFrame.MAXIMIZED_BOTH);
        homeWithOutLog.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnBackSelectUserActionPerformed

    private void jBtnSaveProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveProjectActionPerformed
        projectService.assignProject(ProjectoSeleccionado.getTitle(), EstudianteSeleccionado);

    }//GEN-LAST:event_jBtnSaveProjectActionPerformed

    private void jTableProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProjectsMouseClicked
        int selectedRow = jTableProjects.getSelectedRow();
        if (selectedRow != -1) {
            String codigo = jTableProjects.getValueAt(selectedRow, 0).toString(); // Suponiendo que la primera columna es el código
            ProjectoSeleccionado = projectService.searchTitle(codigo);

            if (ProjectoSeleccionado != null) {
                jLabelNameProject.setText(ProjectoSeleccionado.getTitle());
            }
        }
    }//GEN-LAST:event_jTableProjectsMouseClicked

    private void jTableStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStudentMouseClicked
        int selectedRow = jTableStudent.getSelectedRow();
        if (selectedRow != -1) {
            String codigo = jTableStudent.getValueAt(selectedRow, 0).toString(); // Suponiendo que la primera columna es el código
            EstudianteSeleccionado = studentService.Search(codigo);

            if (EstudianteSeleccionado != null) {
                jLStudent.setText(EstudianteSeleccionado.getName());
            }
        }
    }//GEN-LAST:event_jTableStudentMouseClicked

      public void fillStudents() {
        DefaultTableModel modeloStudent = new DefaultTableModel(new String[]{"Codigo", "Nombre", "Email"}, 0);
        modeloStudent.setRowCount(0);

        if (studentService != null) {
            for (Student student : studentService.listAll()) {

                if (student.getName() != null && student.getCode() != null) {
                    modeloStudent.addRow(new Object[]{student.getCode(), student.getName(), student.getEmail()});
                }
                jTableStudent.setModel(modeloStudent);
            }
        }
    }
      
       public void fillTableProject() {
        DefaultTableModel modeloProyectos = new DefaultTableModel(new String[]{"Titulo", "descripcion", "Comapañia", "Estudiante encargado"}, 0);
        modeloProyectos.setRowCount(0);

        for (Project project : projectService.getAllProjects()) {

            if (project.getStudent() != null && project.getStudent().getName() != null) {
                modeloProyectos.addRow(new Object[]{project.getTitle(), project.getDescription(), project.getTituloEmpresa(), project.getStudent().getName()});
            } else {
                modeloProyectos.addRow(new Object[]{project.getTitle(), project.getDescription(), project.getTituloEmpresa(), "no tiene"});
            }
        }
        jTableProjects.setModel(modeloProyectos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadiobuttonGroupSelecRol;
    private javax.swing.JButton jBtnBackSelectUser;
    private javax.swing.JButton jBtnSaveProject;
    private javax.swing.JLabel jLStudent;
    private javax.swing.JLabel jLTittleNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNameProject;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPProjects;
    private javax.swing.JPanel jPStudent;
    private javax.swing.JPanel jPTittleNewUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProjects;
    private javax.swing.JTable jTableStudent;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        fillTableProject();
        fillStudents();
    }
}
